name = "cloudflare-works-test"
main = "src/handler.ts"
compatibility_date = "2023-01-01"

# wrangler.toml (wrangler v3.88.0^) 启用日志
[observability.logs]
enabled = true

[vars]
# 开发时的默认值，生产环境请在 Cloudflare Dashboard 中设置
OPENROUTER_API_KEY = ""  # 开发时的默认值
APP_REFERER = ""  # 你的域名
APP_TITLE = ""    # 你的应用名称




